name: Deploy fram-data Documentation

on:
#  push:
#    branches:
#      - main
#    paths:
#      - 'docs/**'
#      - 'framcore/**'
#      - 'mkdocs.yml'
  workflow_dispatch:

jobs:
  deploy-docs:
    uses: ./.github/workflows/template_publish_docs.yml
    permissions:
      contents: write
    with:
      package_name: 'framdata'
      source_paths: '["docs/**", "framdata/**", "mkdocs.yml"]'
